---
title: "101 project"
author: "Hamad Tria"
date: "2023-05-30"
output: html_document
---

```{r}
library(tidyr)
library(ggplot2)
library(gridExtra)
library(formattable)
library(knitr)
options(knitr.kable.NA = '')
```

# Sampling

```{r setup, include=FALSE}
set.seed(1)
assign_within <- matrix(rep(c(NA, NA, NA, NA), 108), nrow = 108)
for (i in seq_len(108)){
  assign_within[i,] <- sample(c("0", "1", "2", "3"), 4)
}
assign_between <- matrix(sample(1:108, 54, replace = FALSE), nrow = 54)
write.csv(assign_within, "within")

sample(c("0", "1", "2", "3"), 4)
```

# Tidying the data

```{r}
data <- read.csv("Stats 101B - Final Project - Sheet2.csv", header = TRUE)

day1 <- as.data.frame(cbind(id = data$X, name = data$name, drug = data$drug,
                            dose = data$dose.day.1, score = data$score.day.1))
day2 <- as.data.frame(cbind(id = data$X, name = data$name, drug = data$drug, 
                            dose = data$dose.day.2, score = data$score.day.2))
day3 <- as.data.frame(cbind(id = data$X, name = data$name, drug = data$drug, 
                            dose = data$dose.day.3, score = data$score.day.3))
day4 <- as.data.frame(cbind(id = data$X, name = data$name, drug = data$drug, 
                            dose = data$dose.day.4, score = data$score.day.4))

df <- rbind(day1, day2, day3, day4)
df$drug[df$drug == "N"] <- "Nicotine"
df$drug[df$drug == "C"] <- "Caffeine"
df$score <- as.numeric(df$score)
df$name <- factor(df$name)
df$dose <- factor(df$dose)
df$drug <- factor(df$drug)
df$id <- factor(df$id)

df
```

# Comparisons

```{r}
aggregate(score~drug, FUN = mean, data = df)
aggregate(score~dose, FUN = mean, data = df)
```

```{r}
ggplot(df, aes(x=dose, y=score, fill=drug)) +
  geom_boxplot(position=position_dodge(1)) +
  ggtitle("Distributional spread of scores per dose across drugs") +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_grid(~drug)
```

```{r}
ggplot(df, aes(x=drug, y=score, fill=dose)) +
  geom_boxplot(position=position_dodge(1)) +
  ggtitle("Distributional spread of scores per drugs across dose") +
  theme(plot.title = element_text(hjust = 0.5))+
  facet_grid(~dose)
```

```{r}
attach(df)
ggplot() + aes(x = dose, color = drug, group = drug, y = score) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line")
```

```{r}
model <- aov(score~ drug * dose + Error(factor(name)), data = df)
t <- summary(model)

class(t$`Error: factor(name)`) <- NULL
class(t$`Error: Within`) <- NULL
class(t) <- NULL

kable(t$`Error: factor(name)`, digits = 3, format = "pandoc", caption = "ANOVA table Error: factor(name)")
kable(t$`Error: Within`, digits = 3, format = "pandoc", caption = "ANOVA table Error: Within")
```


```{r}
#install.packages("afex")
library(afex)
```


```{r}
model2 <- aov_4(score~ drug * dose + Error(factor(name)), data = df)
```

```{r}
new_dat <- fitted(model, append=TRUE)
```

```{r}
residuals_tmp <- residuals(model, append=TRUE)
```

```{r}
new_dat$.residuals <- residuals_tmp$.residuals
```

```{r}
head(new_dat, 20)
```

```{r}
#model <- aov(score ~ drug * dose + Error(factor(name)), data = df)

tukey_results <- TukeyHSD(model)

print(tukey_results)

```

```{r}
library(lsmeans)
```

```{r}

#model <- aov(score ~ drug * dose + Error(factor(name)), data = df)

tukey_results <- lsmeans(model, pairwise ~ drug * dose, adjust = "tukey")

print(tukey_results)
```

```{r}
typeof(model)
```

```{r}
TukeyHSD(model)
```

```{r}
class(model)
```

